### ISSUE TITLE
What about attribution?

### ISSUE THREAD

**Issue by Alvarito050506** [MegaTKC/Feather#1]
Hello!

I just found this project, and noticed it's basically a reupload of TheBrokenRail's branch of [MCPI-Revival/Pocketmine-MP](/MCPI-Revival/Pocketmine-MP). While it doesn't look like you broke the license, and I haven't contributed to that project in particular, I don't think it's cool that you simply reuploaded the project without its commit history and then erased mentions of its origin from the source code, without making any real change to its functionality.

Then in your documentation about the project you claim that it was "created" for MCPI-Reborn, and you also do a comparison between MCPI-Reborn server and Feather, but two<sup>[1][1][2][2]</sup> out of three of MCPI-Reborn's disadvantages don't really exist.

Please consider at least restoring the attribution and editing the comparison to be accurate.

[1]: /MegaTKC/megatkc.github.io/blob/main/documentation/feather/feather-vs-other-server-software.md?plain=1#L29
[2]: /MegaTKC/megatkc.github.io/blob/main/documentation/feather/feather-vs-other-server-software.md?plain=1#L31

**Comment by MegaTKC** [comment]
> Hello!
> 
> I just found this project, and noticed it's basically a reupload of TheBrokenRail's branch of [MCPI-Revival/Pocketmine-MP](/MCPI-Revival/Pocketmine-MP). While it doesn't look like you broke the license, and I haven't contributed to that project in particular, I don't think it's cool that you simply reuploaded the project without its commit history and then erased mentions of its origin from the source code, without making any real change to its functionality.
> 
> Then in your documentation about the project you claim that it was "created" for MCPI-Reborn, and you also do a comparison between MCPI-Reborn server and Feather, but two[1](/MegaTKC/megatkc.github.io/blob/main/documentation/feather/feather-vs-other-server-software.md?plain=1#L29)[2](/MegaTKC/megatkc.github.io/blob/main/documentation/feather/feather-vs-other-server-software.md?plain=1#L31) out of three of MCPI-Reborn's disadvantages don't really exist.
> 
> Please consider at least restoring the attribution and editing the comparison to be accurate.

Alright, thanks. This does make sense. I will edit the comparison and restore the attribution.

**Comment by Alvarito050506** [comment]
Thanks! It's appreciated.
